#!/bin/bash

echo "Enter your project name(do not type uppercase)"
read projectName

npx create-next-app --typescript "$projectName"
cd "$projectName"
npx install-peerdeps --dev eslint-config-airbnb
npm install -D eslint-config-prettier eslint-plugin-prettier

echo "{" > .eslintrc.json
echo "  \"extends\": [\"airbnb\", \"plugin:prettier/recommended\", \"next/core-web-vitals\"]," >> .eslintrc.json
echo "  \"rules\": {" >> .eslintrc.json
echo "    \"react/jsx-filename-extension\": [" >> .eslintrc.json
echo "      2," >> .eslintrc.json
echo "      { \"extensions\": [\".js\", \".jsx\", \".ts\", \".tsx\"] }" >> .eslintrc.json
echo "    ]," >> .eslintrc.json
echo "    \"react/function-component-definition\": [" >> .eslintrc.json
echo "      2," >> .eslintrc.json
echo "      {" >> .eslintrc.json
echo "        \"namedComponents\": \"arrow-function\"," >> .eslintrc.json
echo "        \"unnamedComponents\": \"arrow-function\"" >> .eslintrc.json
echo "      }" >> .eslintrc.json
echo "    ]," >> .eslintrc.json
echo "    \"prettier/prettier\": [\"error\"]," >> .eslintrc.json
echo "    \"react/jsx-props-no-spreading\": \"off\"" >> .eslintrc.json
echo "  }" >> .eslintrc.json
echo "}" >> .eslintrc.json

echo "{" > .prettierrc.json
echo "  \"printWidth\": 80," >> .prettierrc.json
echo "  \"semi\": true," >> .prettierrc.json
echo "  \"singleQuote\": true," >> .prettierrc.json
echo "  \"trailingComma\": \"all\"," >> .prettierrc.json
echo "  \"tabWidth\": 2," >> .prettierrc.json
echo "  \"bracketSpacing\": true," >> .prettierrc.json
echo "  \"endOfLine\": \"auto\"," >> .prettierrc.json
echo "  \"useTabs\": false" >> .prettierrc.json
echo "}" >> .prettierrc.json


echo import \'../styles/globals.css\'\; > ./pages/_app.tsx
echo import type \{ AppProps \} from \'next/app\'\; >> ./pages/_app.tsx
echo >> ./pages/_app.tsx
echo const MyApp = \(\{ Component, pageProps \}: AppProps\) =\> \{ >> ./pages/_app.tsx
echo "  return <Component {...pageProps} />;" >> ./pages/_app.tsx
echo \}\; >> ./pages/_app.tsx
echo >> ./pages/_app.tsx
echo export default MyApp\; >> ./pages/_app.tsx

echo "import type { NextPage } from 'next';" > ./pages/index.tsx
echo "import Head from 'next/head';" >> ./pages/index.tsx
echo "import Image from 'next/image';" >> ./pages/index.tsx
echo "import styles from '../styles/Home.module.css';" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "const Home: NextPage = () => {" >> ./pages/index.tsx
echo "  return (" >> ./pages/index.tsx
echo "    <div className={styles.container}>" >> ./pages/index.tsx
echo "      <Head>" >> ./pages/index.tsx
echo "        <title>Create Next App</title>" >> ./pages/index.tsx
echo "        <meta name=\"description\" content=\"Generated by create next app\" />" >> ./pages/index.tsx
echo "        <link rel=\"icon\" href=\"/favicon.ico\" />" >> ./pages/index.tsx
echo "      </Head>" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "      <main className={styles.main}>" >> ./pages/index.tsx
echo "        <h1 className={styles.title}>" >> ./pages/index.tsx
echo "          Welcome to <a href=\"https://nextjs.org\">Next.js!</a>" >> ./pages/index.tsx
echo "        </h1>" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "        <p className={styles.description}>" >> ./pages/index.tsx
echo "          Get started by editing{' '}" >> ./pages/index.tsx
echo "          <code className={styles.code}>pages/index.tsx</code>" >> ./pages/index.tsx
echo "        </p>" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "        <div className={styles.grid}>" >> ./pages/index.tsx
echo "          <a href=\"https://nextjs.org/docs\" className={styles.card}>" >> ./pages/index.tsx
echo "            <h2>Documentation &rarr;</h2>" >> ./pages/index.tsx
echo "            <p>Find in-depth information about Next.js features and API.</p>" >> ./pages/index.tsx
echo "          </a>" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "          <a href=\"https://nextjs.org/learn\" className={styles.card}>" >> ./pages/index.tsx
echo "            <h2>Learn &rarr;</h2>" >> ./pages/index.tsx
echo "            <p>Learn about Next.js in an interactive course with quizzes!</p>" >> ./pages/index.tsx
echo "          </a>" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "          <a" >> ./pages/index.tsx
echo "            href=\"https://github.com/vercel/next.js/tree/canary/examples\"" >> ./pages/index.tsx
echo "            className={styles.card}" >> ./pages/index.tsx
echo "          >" >> ./pages/index.tsx
echo "            <h2>Examples &rarr;</h2>" >> ./pages/index.tsx
echo "            <p>Discover and deploy boilerplate example Next.js projects.</p>" >> ./pages/index.tsx
echo "          </a>" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "          <a" >> ./pages/index.tsx
echo "            href=\"https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app\"" >> ./pages/index.tsx
echo "            className={styles.card}" >> ./pages/index.tsx
echo "          >" >> ./pages/index.tsx
echo "            <h2>Deploy &rarr;</h2>" >> ./pages/index.tsx
echo "            <p>" >> ./pages/index.tsx
echo "              Instantly deploy your Next.js site to a public URL with Vercel." >> ./pages/index.tsx
echo "            </p>" >> ./pages/index.tsx
echo "          </a>" >> ./pages/index.tsx
echo "        </div>" >> ./pages/index.tsx
echo "      </main>" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "      <footer className={styles.footer}>" >> ./pages/index.tsx
echo "        <a" >> ./pages/index.tsx
echo "          href=\"https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app\"" >> ./pages/index.tsx
echo "          target=\"_blank\"" >> ./pages/index.tsx
echo "          rel=\"noopener noreferrer\"" >> ./pages/index.tsx
echo "        >" >> ./pages/index.tsx
echo "          Powered by{' '}" >> ./pages/index.tsx
echo "          <span className={styles.logo}>" >> ./pages/index.tsx
echo "            <Image src=\"/vercel.svg\" alt=\"Vercel Logo\" width={72} height={16} />" >> ./pages/index.tsx
echo "          </span>" >> ./pages/index.tsx
echo "        </a>" >> ./pages/index.tsx
echo "      </footer>" >> ./pages/index.tsx
echo "    </div>" >> ./pages/index.tsx
echo "  );" >> ./pages/index.tsx
echo "};" >> ./pages/index.tsx
echo "" >> ./pages/index.tsx
echo "export default Home;" >> ./pages/index.tsx

echo "// Next.js API route support: https://nextjs.org/docs/api-routes/introduction" > ./pages/api/hello.ts
echo "import type { NextApiRequest, NextApiResponse } from 'next';" >> ./pages/api/hello.ts
echo "" >> ./pages/api/hello.ts
echo "type Data = {" >> ./pages/api/hello.ts
echo "  name: string;" >> ./pages/api/hello.ts
echo "};" >> ./pages/api/hello.ts
echo "" >> ./pages/api/hello.ts
echo "export default function handler(" >> ./pages/api/hello.ts
echo "  req: NextApiRequest," >> ./pages/api/hello.ts
echo "  res: NextApiResponse<Data>," >> ./pages/api/hello.ts
echo ") {" >> ./pages/api/hello.ts
echo "  res.status(200).json({ name: 'John Doe' });" >> ./pages/api/hello.ts
echo "}" >> ./pages/api/hello.ts

echo "{" > tsconfig.json
echo "  \"compilerOptions\": {" >> tsconfig.json
echo "    \"target\": \"es5\"," >> tsconfig.json
echo "    \"lib\": [\"dom\", \"dom.iterable\", \"esnext\"]," >> tsconfig.json
echo "    \"allowJs\": true," >> tsconfig.json
echo "    \"skipLibCheck\": true," >> tsconfig.json
echo "    \"strict\": true," >> tsconfig.json
echo "    \"forceConsistentCasingInFileNames\": true," >> tsconfig.json
echo "    \"noEmit\": true," >> tsconfig.json
echo "    \"esModuleInterop\": true," >> tsconfig.json
echo "    \"module\": \"esnext\"," >> tsconfig.json
echo "    \"moduleResolution\": \"node\"," >> tsconfig.json
echo "    \"resolveJsonModule\": true," >> tsconfig.json
echo "    \"isolatedModules\": true," >> tsconfig.json
echo "    \"jsx\": \"preserve\"," >> tsconfig.json
echo "    \"incremental\": true," >> tsconfig.json
echo "    \"baseUrl\": \".\"," >> tsconfig.json
echo "    \"paths\": {" >> tsconfig.json
echo "      \"@components/*\": [\"components/*\"]," >> tsconfig.json
echo "      \"@layouts/*\": [\"layouts/*\"]," >> tsconfig.json
echo "      \"@pages/*\": [\"pages/*\"]," >> tsconfig.json
echo "      \"@public/*\": [\"public/*\"]," >> tsconfig.json
echo "      \"@styles/*\": [\"styles/*\"]," >> tsconfig.json
echo "      \"@utils/*\": [\"utils/*\"]," >> tsconfig.json
echo "      \"@hooks/*\": [\"hooks/*\"]," >> tsconfig.json
echo "      \"@interfaces/*\": [\"interfaces/*\"]" >> tsconfig.json
echo "    }" >> tsconfig.json
echo "  }," >> tsconfig.json
echo "  \"include\": [\"next-env.d.ts\", \"**/*.ts\", \"**/*.tsx\"]," >> tsconfig.json
echo "  \"exclude\": [\"node_modules\"]" >> tsconfig.json
echo "}" >> tsconfig.json

mkdir components
mkdir layouts
mkdir utils
mkdir hooks
mkdir interfaces

echo "# My $projectName App" > README.md
